Repository qax-os/excelize, pull requests merged in 2021-06, with the labels that each got.

#853 #409 Remove UTC timezone requirement from date.go
  date.go
  date_test.go
  excelize_test.go
  stream_test.go
Labels: size/XS

#857 fixes https://github.com/360EntSecGroup-Skylar/excelize/issues/856
  calc.go
  calc_test.go
Labels: size/S

#859 fixes https://github.com/360EntSecGroup-Skylar/excelize/issues/858
  calc.go
  calc_test.go
Labels: size/S

#860 fix getRowHeight actually get the height of the next row
  rows.go
Labels: size/XS

#863 feat: stream write to zip directly
  file.go
  file_test.go
Labels: size/M
