Repository qax-os/excelize, pull requests merged in 2021-12, with the labels that each got.

#1077 Fix call getNumFmtID with builtInNumFmt return -1
  styles.go
  styles_test.go
Labels: size/S

#1078 refactor DeleteSheet for better readability
  sheet.go
Labels: size/M

#1082 Fix adjustMergeCellsHelper and add some test cases
  adjust.go
  adjust_test.go
Labels: size/L

#1092 Fixes issue 1090
  calc.go
  calc_test.go
Labels: size/S

#1108 Compatible with Tabs
  cell.go
Labels: size/XS
