Repository qax-os/excelize, pull requests merged in 2021-08, with the labels that each got.

#988 excelize: support nested calc for if formula
  calc.go
  calc_test.go
Labels: size/S

#968 Mergecell speed
  adjust.go
  adjust_test.go
  calc.go
  cell.go
  col.go
  lib.go
  merge.go
  merge_test.go
  picture.go
  pivotTable.go
  rows.go
  sheet.go
  xmlSharedStrings.go
  xmlWorksheet.go
Labels: size/L

#846 fix shared formula incorrect (#844)
  cell.go
  cell_test.go
  excelize_test.go
  lib.go
Labels: size/M

#996 fix LOOKUP function for Array form
  calc.go
  calc_test.go
Labels: size/S

#1003 Implement DAY function
  calc.go
  calc_test.go
  date.go
Labels: size/S

#1001 Fix LOOKUP function to find nearest match
  calc.go
  calc_test.go
Labels: size/S

#1005 Implement MONTH function
  calc.go
  calc_test.go
Labels: size/M

#1007 Implement YEAR function
  calc.go
  calc_test.go
Labels: size/M
