Repository qax-os/excelize, pull requests merged in 2022-12, with the labels that each got.

#1415 Fix binary string regex
  lib.go
  lib_test.go
Labels: size/S

#1422 issue 1416
  stream.go
  stream_test.go
Labels: size/M

#1426 Detect invalid characters when setting sheet name, if invalid, report an error
  calc.go
  calc_test.go
  cell_test.go
  chart.go
  chart_test.go
  col.go
  col_test.go
  comment.go
  comment_test.go
  datavalidation_test.go
  errors.go
  excelize.go
  excelize_test.go
  merge_test.go
  picture_test.go
  pivotTable_test.go
  rows.go
  rows_test.go
  shape_test.go
  sheet.go
  sheet_test.go
  sheetpr_test.go
  sparkline_test.go
  stream.go
  stream_test.go
  styles.go
  styles_test.go
  table.go
  table_test.go
  workbook.go
  xmlComments.go
  xmlDrawing.go
Labels: size/L

#1431 feat: support workbook protection
  crypt.go
  errors.go
  excelize_test.go
  workbook.go
  xmlWorkbook.go
Labels: size/L

#1433 Fix panic formattedValue when style is negative
  cell.go
  cell_test.go
Labels: size/XS
