Repository qax-os/excelize, pull requests merged in 2022-07, with the labels that each got.

#1270 bugfix: sheet name is case-insensitive
  sheet.go
  sheet_test.go
Labels: size/XS

#1272 Improve column number error handling
  calc.go
  errors.go
  lib.go
  lib_test.go
  sheet.go
  stream.go
  stream_test.go
  xmlDrawing.go
Labels: size/M

#1281 refine comments for file.go
  file.go
Labels: size/XS

#1285 add support for more tabColor options and split RGB #1283
  sheetpr.go
  sheetpr_test.go
Labels: size/L
