Repository qax-os/excelize, pull requests merged in 2022-08, with the labels that each got.

#1301 #1299 don't write nil values in SetRow
  stream.go
  stream_test.go
Labels: size/S

#1311 #1310 existing comment shapes should be load only once
  comment.go
Labels: size/S

#1297 #1296 add GetRowOpts to Rows
  rows.go
  rows_test.go
  sheet.go
  sheet_test.go
  test/Book1.xlsx
  xmlDrawing.go
Labels: size/L

#1317 feat: DelComment
  comment.go
  comment_test.go
  docProps.go
  drawing.go
  errors.go
  excelize.go
  picture.go
  stream.go
Labels: size/M

#1324 Support encrypt workbook with password #199
  crypt.go
  crypt_test.go
Labels: size/XL

#1320 Added function SetSheetCol to replicate SetSheetRow behavior for columns
  cell.go
  excelize_test.go
Labels: size/M

#1315 Initialize GetDataValidation and GetConditionalFormat for sheets
  datavalidation.go
  datavalidation_test.go
  excelize_test.go
  styles.go
  styles_test.go
  xmlWorksheet.go
Labels: size/L

#1331 #1330 update non existing sheet error messages
  adjust_test.go
  calc_test.go
  cell_test.go
  chart_test.go
  col_test.go
  comment_test.go
  datavalidation_test.go
  errors.go
  excelize_test.go
  merge_test.go
  picture_test.go
  pivotTable.go
  pivotTable_test.go
  rows.go
  rows_test.go
  shape_test.go
  sheet_test.go
  sheetpr_test.go
  sparkline_test.go
  stream_test.go
  styles.go
  styles_test.go
  table_test.go
Labels: size/M

#1333 Add batch rows insertion function
  adjust.go
  adjust_test.go
  col.go
  col_test.go
  rows.go
  rows_test.go
Labels: size/M
