Repository qax-os/excelize, pull requests merged in 2023-11, with the labels that each got.

#1710 Fix: scientific notation zerofill issues
  numfmt.go
  numfmt_test.go
Labels: size/XS

#1127 Support update drawing objects on inserting/deleting columns/rows
  adjust.go
  adjust_test.go
  picture.go
  picture_test.go
  xmlDecodeDrawing.go
  xmlDrawing.go
Labels: size/L

#1713 Reduce memory consumption
  sheet.go
Labels: size/S

#1714 feat: setRange support list type
  datavalidation.go
  datavalidation_test.go
Labels: size/M

#1717 Support update conditional formatting on inserting/deleting columns/rows
  adjust.go
  adjust_test.go
  datavalidation_test.go
  excelize_test.go
  styles.go
  styles_test.go
Labels: size/M

#1718 Support set time period type conditional formatting
  styles.go
  styles_test.go
Labels: size/M

#1720 This adds new exported function GetHeaderFooter
  sheet.go
  sheet_test.go
Labels: size/M

#1721 Fix panic on GetPictureCells without drawing relationships parts
  picture.go
Labels: size/XS

#1692 Update checkSheet GetTables error: index out of range
  adjust.go
  adjust_test.go
  cell.go
  cell_test.go
  col.go
  col_test.go
  excelize.go
  rows.go
  sheet.go
  xmlWorksheet.go
Labels: size/L

#1724 The GetCellRichText function support to return inline rich text
  cell.go
  cell_test.go
Labels: size/M

#1725 Fix invalid shared string table index on set cell value
  cell.go
Labels: size/XS

#1728 This support set column style with default width in sheet props settings
  col.go
  col_test.go
Labels: size/S

#1733 This closes #1729, support copy conditional format and data validation on duplicate row
  rows.go
  rows_test.go
Labels: size/L

#1735 This closes #1732, saving workbook with sorted internal part path
  file.go
Labels: size/S
