Repository qax-os/excelize, pull requests merged in 2023-02, with the labels that each got.

#1467 Allow user to set sheet dimension element
  sheet.go
  sheet_test.go
Labels: size/M

#1470 Fixes #1469
  calc.go
  calc_test.go
Labels: size/M

#1477 1476: Support double-byte chars for LEFT(),RIGHT(), LEN() and MID().
  calc.go
  calc_test.go
Labels: size/S

#1478 1476: Test codes and Byte process
  calc.go
  calc_test.go
Labels: size/M

#1481 Fixes #756 remove empty string when set cell value to nil in Stream W…
  stream.go
Labels: size/XS
