Repository qax-os/excelize, pull requests merged in 2023-10, with the labels that each got.

#1684 Fix: Issue ##1682 - Delete table
  table.go
  table_test.go
Labels: size/S

#1685 Remove redundant `len` check in `GroupSheets` and `UngroupSheets`
  sheet.go
Labels: size/XS

#1698 Update adjustFormula
  adjust.go
  adjust_test.go
  calc.go
  calc_test.go
  lib.go
  rows.go
  rows_test.go
  xmlCalcChain.go
Labels: size/L

#1702 Add tests for adjusting formula
  adjust.go
  adjust_test.go
  rows.go
Labels: size/L

#1705 Add feature to update references to other worksheets
  adjust.go
  adjust_test.go
  rows.go
Labels: size/L
