Repository qax-os/excelize, pull requests merged in 2023-12, with the labels that each got.

#1736 Support unset custom row height if height value is -1
  rows.go
  rows_test.go
Labels: size/S

#1747 fix some function names in comment
  cell.go
  crypt.go
  slicer.go
  styles.go
Labels: size/XS

#1746 Remove unused struct
  xmlDrawing.go
Labels: size/XS

#1753 This closes #1749, fix incorrect adjust merged cells on remove rows
  adjust.go
  rows_test.go
Labels: size/S

#1755 This closes # 1704,support set the data labels position for the chart
  chart.go
  chart_test.go
  drawing.go
  templates.go
  xmlChart.go
Labels: size/L

#1759 This closes #664, support get embedded cell images
  calc.go
  calc_test.go
  chart.go
  excelize.go
  picture.go
  picture_test.go
  templates.go
  xmlDecodeDrawing.go
Labels: size/L
