Repository qax-os/excelize, pull requests merged in 2023-03, with the labels that each got.

#1485 This closes #1484, fix formula calc result issue
  calc.go
  datavalidation.go
  datavalidation_test.go
Labels: size/L

#1490 Fix NA error
  calc.go
  calc_test.go
Labels: size/XXL

#1500 #1448 Enhances the performance of checkCellInRangeRef and merging cells.
  cell.go
Labels: size/M
