Repository qax-os/excelize, pull requests merged in 2024-03, with the labels that each got.

#1828 Feat: AddDataValidation() and DeleteDataValidation() are concurrency safe, and add some unit test and code optimization.
  adjust.go
  cell_test.go
  datavalidation.go
  lib.go
  lib_test.go
  rows.go
  sheet.go
  stream.go
  table.go
Labels: size/M

#1837 Optimize `getSharedFormula` to avoid `runtime.duffcopy`
  cell.go
Labels: size/XS

#1834 Support for the new method GetAllLinkedDataValidations to retrieve data validation content from linked sheets.
  cell_test.go
  datavalidation.go
  datavalidation_test.go
  templates.go
  xmlWorksheet.go
Labels: size/L

#1846 chore: fix typo
  styles.go
Labels: kind/documentation, size/XS

#1849 This fix performance impact introduced in #1692
  adjust.go
  adjust_test.go
  cell.go
  cell_test.go
  col.go
  col_test.go
  excelize.go
  rows.go
  sheet.go
  xmlWorksheet.go
Labels: size/M

#1852 This closes #1847, support apply number format with alignment
  excelize_test.go
  go.mod
  go.sum
  numfmt.go
  numfmt_test.go
Labels: size/M

#1860 This closes #1851, fix formula calculation result round issue
  calc.go
  calc_test.go
  sheet.go
  sheet_test.go
Labels: size/M

#1857 Add support for getting cell-embedded pictures/images
  excelize.go
  picture.go
  picture_test.go
  templates.go
  xmlMetaData.go
Labels: size/L

#1864 Introduce exported PictureInsertType enumeration
  picture.go
  picture_test.go
  xmlDrawing.go
Labels: size/M

#1866 Support get rich data value rels index from rich value part
  excelize.go
  picture.go
  picture_test.go
  templates.go
  xmlMetaData.go
Labels: size/L
