Repository qax-os/excelize, pull requests merged in 2024-06, with the labels that each got.

#1924 This closes #1921, fix set axis format doesn't work in combo chart
  drawing.go
Labels: size/L

#1923 Support filling images in cells
  picture.go
  picture_test.go
  xmlDrawing.go
Labels: size/S

#1928 fixes issue #1926
  drawing.go
Labels: size/XS
