Repository qax-os/excelize, pull requests merged in 2024-09, with the labels that each got.

#1988 Support absolute paths for `GetPictureCells` and `GetPictures` functions
  picture.go
  picture_test.go
Labels: size/M

#1992 Added new formula function DOLLAR
  calc.go
  calc_test.go
Labels: size/M

#2000 closes #1999,fix GetCellRichText strconv.Atoi error because of null value (#1999)
  .github/workflows/go.yml
  cell.go
  cell_test.go
  errors.go
  go.mod
  go.sum
Labels: size/S

#1996 #1076 Add MoveSheet and SwapSheets functions to support changing sheet order in the workbook
  sheet.go
  sheet_test.go
Labels: size/L
