Repository qax-os/excelize, pull requests merged in 2024-08, with the labels that each got.

#1943 Add new functions DeleteSlicer and GetSlicers
  errors.go
  pivotTable.go
  pivotTable_test.go
  slicer.go
  slicer_test.go
  table.go
  xmlDecodeDrawing.go
  xmlSlicers.go
Labels: size/XL

#1951 Improve the compatibility of the number format
  numfmt.go
  numfmt_test.go
Labels: size/L

#1984 This closes #1979, fix decimal value round issue
  numfmt.go
  numfmt_test.go
Labels: size/S
