Repository qax-os/excelize, pull requests merged in 2024-07, with the labels that each got.

#1935 Optimize ColumnNumberToName function performance, reduce about 50% memory usage and 50% time cost
  lib.go
Labels: size/XS

#1941 This closes #1937,fix getPivotTable use wrong sheetName (#1937)
  go.mod
  go.sum
  merge.go
  pivotTable.go
  pivotTable_test.go
Labels: size/S

#1946 Add new TickLabelPosition field in the ChartAxis data type
  chart.go
  chart_test.go
  drawing.go
  xmlChart.go
Labels: size/M

#1947 This closes #1942, fix percent sign missing in formatted cell value
  numfmt.go
  numfmt_test.go
Labels: size/S
