Repository qax-os/excelize, pull requests merged in 2025-01, with the labels that each got.

#2064 This closes #2061, fix border styles missing after saved workbook
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  numfmt.go
  styles.go
  xmlStyles.go
Labels: size/L

#2066 fix function name
  sheetpr.go
Labels: size/XS

#2073 Fix adjustDataValidations skips adjustments on subsequent sheets when the first sheet has no validations
  adjust.go
  adjust_test.go
Labels: size/S

#2076 This close #2075, support streaming writer to set col style
  col.go
  errors.go
  stream.go
  stream_test.go
Labels: size/L

#2079 Fix GetStyle function can not get VertAlign format
  cell.go
  cell_test.go
  go.mod
  go.sum
  stream.go
  stream_test.go
Labels: size/M
