Repository qax-os/excelize, pull requests merged in 2025-03, with the labels that each got.

#2096 reduce memory allocation when possible
  cell.go
Labels: size/XS

#2103 This closes #2102, fix panic on set chart title font
  chart_test.go
  drawing.go
Labels: size/XS

#2109 This closes #2108, Add helper to auto scale sheet on page by single, columns and rows options
  xmlWorksheet.go
Labels: size/L

#2100 replace xml.NewEncoder with xml.EscapeText
  cell.go
Labels: size/XS

#2111 Avoid looking up absent cells in `rangeResolver`
  calc.go
  calc_test.go
Labels: size/M
