Repository qax-os/excelize, pull requests merged in 2025-05, with the labels that each got.

#2123 Fixed drawingResize dimensions calculation
  adjust.go
  adjust_test.go
  chart_test.go
  col.go
  col_test.go
  drawing.go
  picture.go
  picture_test.go
  rows.go
  rows_test.go
  shape.go
  vml.go
Labels: size/L

#2127 DefinedNames SheetNames are not escaped correctly, if a sheet gets renamed
  adjust.go
  sheet_test.go
Labels: size/S

#2128 This related with #2123, made editAs attribute value empty for one cell anchor drawing object
  adjust.go
  cell.go
  chart_test.go
  col.go
  col_test.go
  drawing.go
  picture.go
  rows.go
  rows_test.go
  slicer.go
  xmlDecodeDrawing.go
  xmlDrawing.go
  xmlStyles.go
Labels: size/M

#2129 Using binary search instead of sequential search for rowData
  cell.go
  cell_test.go
Labels: size/S

#2137 Fix: Handle extLst in data validation for deletion (#2133)
  datavalidation.go
  datavalidation_test.go
  xmlWorksheet.go
Labels: size/L

#2142 update comment for datavalidation data structure
  xmlWorksheet.go
Labels: size/XS

#2141 feat(font): add charset support to font definitions
  cell.go
  lib.go
  styles.go
  styles_test.go
  vml.go
  xmlSharedStrings.go
  xmlStyles.go
Labels: size/L

#2143 update comment for add form control function
  README.md
  README_zh.md
  styles.go
  vml.go
Labels: size/XS
