Repository qax-os/excelize, pull requests merged in 2025-06, with the labels that each got.

#2149 Update number format parser, fix parser dropped empty literals in the end of the number format
  go.mod
  go.sum
  numfmt_test.go
Labels: size/XS

#2156 Update dependencies modules
  go.mod
  go.sum
Labels: size/XS

#2147 This close #2146, support setting excel custom properties
  docProps.go
  docProps_test.go
  excelize.go
  file.go
  lib.go
  sheet_test.go
  templates.go
  workbook.go
  xmlCustom.go
Labels: size/L

#2163 This closes #2024, add TempDir field in the Options data type (#2024)
  excelize.go
  lib.go
  rows.go
  stream.go
  stream_test.go
Labels: size/S
